### ISSUE TITLE
ambiguos definitions

### ISSUE THREAD

**Issue by Serbitas** [gordonfn/wqx#6]
What validator is working with this scheme ? I keep getting errors about ambiguos definitions.

Tried ajv and jsonschema packages with the following code:
```javascript
const jsonschema = require('wqx/json-schema/physical-chemistry');
const Ajv = require("ajv")

const ajv = new Ajv()
const validate = ajv.compile(jsonschema)
const valid = validate({})
if (!valid) console.log(validate.errors)
```
resulting in the following error:
Error: reference "https://epa.gov/wqx/TimeZone" resolves to more than one schema

Thanks for the great work!

**Comment by willfarrell** [comment]
Thanks for reporting.

This is from the deref process to create the json schema from its parts. Since, in this case, TimeZone is used for multiple columns, the lingering `$id` is causing this issues. Removing them from all of the properties will resolve this issue.

I've already written this code for the DataStream schema that inherits from this. But haven't found the tim to apply the changes to this repo yet. See https://github.com/datastreamapp/schema/blob/main/schemas/data/bin/build#L7 for the `jq` command to clean up the JSON.

Just an FYI, these JSON schemas don't have cross-column logic built-in at this time.

**Comment by willfarrell** [comment]
I've pushed an update to remove unneeded nested `$id`
